# Frontend (Streamlit UI)
FROM python:3.11.8-slim-bullseye

WORKDIR /app

COPY frontend/ ./frontend/
COPY requirements.txt ./

RUN apt-get update && apt-get upgrade -y && apt-get install -y --no-install-recommends gcc && \
	pip install --no-cache-dir -r requirements.txt && \
	apt-get purge -y --auto-remove gcc && \
	rm -rf /var/lib/apt/lists/*

EXPOSE 8501

CMD ["streamlit", "run", "frontend/app.py", "--server.port=8501", "--server.address=0.0.0.0"]
