version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "5000:5000"
    volumes:
      - ./api:/app/api
      - ./data:/app/data
      - ./model:/app/model
      - ./api_requests.log:/app/api_requests.log
      - ./feedback_log.csv:/app/feedback_log.csv
    environment:
      - FLASK_ENV=production
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app/frontend
    depends_on:
      - api
    command: /bin/sh -c "sleep 10 && streamlit run frontend/app.py --server.port=8501 --server.address=0.0.0.0"
