# Backend (Flask API)
FROM python:3.11-slim

WORKDIR /app

COPY api/ ./api/
COPY data/ ./data/
COPY model/ ./model/
COPY requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 5000

CMD ["python", "api/app.py"]
